#--------------------------------------------------------------------------------
#
# Filename    : Makefile
# Written By  : Reiot
#
#--------------------------------------------------------------------------------

#--------------------------------------------------------------------------------
# Directories
#--------------------------------------------------------------------------------
VSHOME  = ../../..
STLDIR  = /usr/include/STL
BINDIR  = $(VSHOME)/bin
LIBDIR  = $(VSHOME)/lib
SRCDIR  = $(VSHOME)/src
COREDIR = ..
SERVDIR = ../../server
DBDIR   = $(SERVDIR)/database
GSDIR   = $(SERVDIR)/gameserver
LSDIR   = $(SERVDIR)/loginserver
SSDIR	= $(SERVDIR)/sharedserver
CLIDIR  = ../../client
LCCDIR  = $(CLIDIR)/linux/console


#--------------------------------------------------------------------------------
# General Rules
#--------------------------------------------------------------------------------
.SUFFIXES : .cpp .gs.o .ls.o .ss.o

CC       = g++
DEFS     = -D__LINUX__ -D_REENTRANT
INCLUDES = -I$(STLDIR) -I$(COREDIR)
CCFLAGS  = -Wall -c -g 
#CCFLAGS  = -Wall -c -g 

TARGET1 = $(LIBDIR)/libGameServerPackets.a
TARGET2 = $(LIBDIR)/libLoginServerPackets.a
TARGET3 = $(LIBDIR)/libLinuxConsoleClientPackets.a
TARGET4 = $(LIBDIR)/libSharedServerPackets.a

OBJS1	= \
		RCSay.gs.o RCSayHandler.gs.o

OBJS2	= \
		RCSay.ls.o RCSayHandler.ls.o

OBJS4	= \
		RCSay.ss.o RCSayHandler.ss.o

SRCS	= $(OBJS1:.gs.o=.cpp)

.cpp.gs.o : 
	$(CC) $(CCFLAGS) $(DEFS) -D__GAME_SERVER__ $(INCLUDES) -I$(SERVDIR) -I$(GSDIR) -I$(DBDIR) -o $*.gs.o $<

.cpp.ls.o : 
	$(CC) $(CCFLAGS) $(DEFS) -D__LOGIN_SERVER__ $(INCLUDES) -I$(SERVDIR) -I$(LSDIR) -I$(DBDIR) -o $*.ls.o $<

.cpp.ss.o :
	$(CC) $(CCFLAGS) $(DEFS) -D__SHARED_SERVER__ $(INCLUDES) -I$(SERVDIR) -I$(SSDIR) -I$(DBDIR) -o $*.ss.o $<

#--------------------------------------------------------------------------------
# Actions
#--------------------------------------------------------------------------------

#all : $(TARGET1) $(TARGET2) $(TARGET3)
all : $(TARGET1) $(TARGET2) $(TARGET4)

allloginserver : $(TARGET2)

allgameserver : $(TARGET1)

allsharedserver : $(TARGET4)

$(TARGET1) : $(OBJS1)
	ar r $@ $(OBJS1)

$(TARGET2) : $(OBJS2)
	ar r $@ $(OBJS2)

$(TARGET3) : $(OBJS3)
	ar r $@ $(OBJS3)

$(TARGET4) : $(OBJS4)
	ar r $@ $(OBJS4)

clean :
	rm -rf *.o

cleanloginserver :
	rm -rf *.ls.o

cleangameserver :
	rm -rf *.gs.o

cleansharedserver :
	rm -rf *.ss.o

cleanall :
	rm -rf *.o

depall :
	gccmakedep $(SRCS) $(INCLUDES) $(DEFS)

dep :
	gccmakedep $(SRCS) $(INCLUDES) $(DEFS)

